manifestVersion = 0

[package]
  type = "mod"
  name = "test-utils"
  description = "Makes mod testing easier. Currently lets you control time and weather without the fuzz."
  version = "0.1.1"
  platform = "fabric"
  license = "MIT"
  source = "https://github.com/minepkg/test-utils"

[requirements]
  minecraft = "~1.17.0"
  fabric = "*"

[dependencies]
  fabric = "*"

[dev]
  buildCommand = "./gradlew build"
