name: minepkg publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download built jar
        uses: actions/download-artifact@v2
        with:
          name: package-${{github.sha}}
          path: build/libs
      - name: install minepkg cli
        run: curl -s https://preview.minepkg.io/install.sh | bash
      - name: publish package
        run: minepkg publish
        env:
          MINEPKG_API_TOKEN: ${{secrets.MINEPKG_API_TOKEN}}
